stages:
  - test

test_ruby_2_4:
  image: ruby:2.4.9
  stage: test
  script:
    - bundle install
    - bundle exec rake

test_ruby_2_5:
  image: ruby:2.5.7
  stage: test
  script:
    - bundle install
    - bundle exec rake

test_ruby_2_6:
  image: ruby:2.6.5
  stage: test
  script:
    - bundle install
    - bundle exec rake
