require: rubocop-rails

Rails:
  Enabled: true

Rails/ApplicationController:
  Enabled: true

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationMailer:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

Rails/BelongsTo:
  Enabled: true

Rails/Date:
  EnforcedStyle: flexible

Rails/EnumHash:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/IgnoredSkipActionFilterOption:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/LinkToBlank:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/SafeNavigationWithBlank:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RedundantForeignKey:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/Pick:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/ContentTag:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/PluckId:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - review
    - staging
    - acceptance
    - training
    - production

# TODO Cops
Rails/AfterCommitOverride: # (new in 2.8)
  Enabled: false
Rails/AttributeDefaultBlockValue: # (new in 2.9)
  Enabled: false
Rails/SquishedSQLHeredocs: # (new in 2.8)
  Enabled: false
Rails/WhereEquals: # (new in 2.9)
  Enabled: false
Rails/WhereNot: # (new in 2.8)
  Enabled: false
