require: rubocop-rails

Rails:
  Enabled: true

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/BelongsTo:
  Enabled: true

Rails/Date:
  EnforcedStyle: flexible

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/IgnoredSkipActionFilterOption:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/LinkToBlank:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - review
    - staging
    - acceptance
    - training
    - production
