require: rubocop-rspec

Capybara/CurrentPathExpectation:
  Enabled: true

Capybara/FeatureMethods:
  Enabled: true

FactoryBot/AttributeDefinedStatically:
  Enabled: true

FactoryBot/CreateList:
  Enabled: true
  EnforcedStyle: create_list

FactoryBot/FactoryClassName:
  Enabled: true

Rails/HttpStatus:
  Enabled: true
  EnforcedStyle: symbolic

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/AnyInstance:
  Enabled: true

RSpec/AroundBlock:
  Enabled: true

RSpec/Be:
  Enabled: true

RSpec/BeEql:
  Enabled: true

RSpec/BeforeAfterAll:
  Enabled: true

RSpec/ContextMethod:
  Enabled: true

RSpec/ContextWording:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true

RSpec/DescribeSymbol:
  Enabled: true

RSpec/DescribedClass:
  Enabled: true
  EnforcedStyle: described_class

RSpec/DescribeMethod:
  Enabled: true

RSpec/Dialect:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: true
  AllowConsecutiveOneLiners: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/ExampleLength:
  Enabled: true
  Max: 5

RSpec/ExampleWithoutDescription:
  Enabled: true
  EnforcedStyle: single_line_only

RSpec/ExampleWording:
  Enabled: true

RSpec/ExpectActual:
  Enabled: true

RSpec/ExpectChange:
  Enabled: true
  EnforcedStyle: block

RSpec/ExpectInHook:
  Enabled: true

RSpec/ExpectOutput:
  Enabled: true

RSpec/FilePath:
  Enabled: true
  IgnoreMethods: false

RSpec/Focus:
  Enabled: true

RSpec/HookArgument:
  Enabled: true
  EnforcedStyle: implicit

RSpec/HooksBeforeExamples:
  Enabled: true

RSpec/ImplicitBlockExpectation:
  Enabled: true

RSpec/ImplicitExpect:
  Enabled: true
  EnforcedStyle: is_expected

RSpec/ImplicitSubject:
  Enabled: true
  EnforcedStyle: single_line_only

RSpec/InstanceSpy:
  Enabled: true

RSpec/InstanceVariable:
  AssignmentOnly: true
  Enabled: true

RSpec/InvalidPredicateMatcher:
  Enabled: true

RSpec/ItBehavesLike:
  Enabled: true
  EnforcedStyle: it_behaves_like

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LeadingSubject:
  Enabled: true

RSpec/LeakyConstantDeclaration:
  Enabled: true

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/LetSetup:
  Enabled: true

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: true
  EnforcedStyle: receive

RSpec/MessageExpectation:
  Enabled: false

RSpec/MissingExampleGroupArgument:
  Enabled: true

RSpec/MultipleDescribes:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5

RSpec/MultipleSubjects:
  Enabled: true

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: true
  Max: 5

RSpec/NotToNot:
  Enabled: false

RSpec/OverwritingSetup:
  Enabled: true

RSpec/Pending:
  Enabled: true

RSpec/PredicateMatcher:
  Enabled: true
  EnforcedStyle: inflected
  Strict: true

RSpec/ReceiveCounts:
  Enabled: false

RSpec/ReceiveNever:
  Enabled: true

RSpec/RepeatedDescription:
  Enabled: true

RSpec/RepeatedExample:
  Enabled: true

RSpec/ReturnFromStub:
  Enabled: true
  EnforcedStyle: and_return

RSpec/ScatteredLet:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: true

RSpec/SharedContext:
  Enabled: true

RSpec/SharedExamples:
  Enabled: true

RSpec/SingleArgumentMessageChain:
  Enabled: true

RSpec/SubjectStub:
  Enabled: true

RSpec/UnspecifiedException:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true

RSpec/VoidExpect:
  Enabled: true

RSpec/Yield:
  Enabled: true

RSpec/RepeatedExampleGroupDescription:
  Enabled: true

RSpec/VariableName:
  Enabled: true

RSpec/VariableDefinition:
  Enabled: true

RSpec/RepeatedExampleGroupBody:
  Enabled: true

RSpec/EmptyHook:
  Enabled: true
